No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/khalevy/miniconda3/lib/python3.11/site-packages/datasets/load.py:2516: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Using the latest cached version of the dataset since chaosarium/c4-cultural-extract couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/khalevy/.cache/huggingface/datasets/chaosarium___c4-cultural-extract/default/0.0.0/8d92c4e063c8ea6e52d2685e38f5d009801b971d (last modified on Sat Apr 27 12:31:01 2024).
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 188, in <module>
    do_retrieval(pipeline, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 161, in do_retrieval
    retrieval_res = pipeline.retrieval_pass(Q)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalevy/Multilingual-Fig-QA/rag/lib/pipeline.py", line 20, in retrieval_pass
    retrieved = self.retriever.query(self.generator.extract_objects(question), k=self.k, lang = self.lang)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WikidataRetriever.query() missing 1 required positional argument: 'model'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/khalevy/miniconda3/lib/python3.11/site-packages/datasets/load.py:2516: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Using the latest cached version of the dataset since chaosarium/c4-cultural-extract couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/khalevy/.cache/huggingface/datasets/chaosarium___c4-cultural-extract/default/0.0.0/8d92c4e063c8ea6e52d2685e38f5d009801b971d (last modified on Sat Apr 27 12:31:01 2024).
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 188, in <module>
    do_retrieval(pipeline, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 161, in do_retrieval
    retrieval_res = pipeline.retrieval_pass(Q)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalevy/Multilingual-Fig-QA/rag/lib/pipeline.py", line 20, in retrieval_pass
    retrieved = self.retriever.query(self.generator.extract_objects(question), k=self.k, lang = self.lang)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WikidataRetriever.query() missing 1 required positional argument: 'model'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/khalevy/miniconda3/lib/python3.11/site-packages/datasets/load.py:2516: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Using the latest cached version of the dataset since chaosarium/c4-cultural-extract couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/khalevy/.cache/huggingface/datasets/chaosarium___c4-cultural-extract/default/0.0.0/8d92c4e063c8ea6e52d2685e38f5d009801b971d (last modified on Sat Apr 27 12:31:01 2024).
slurmstepd: error: *** JOB 258804 ON babel-2-12 CANCELLED AT 2024-04-28T02:22:12 ***
