No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 191, in <module>
    do_evaluation(generator, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 72, in do_evaluation
    with open(f'../experiment/{args.retriever}/{args.lang}/{prefix}retrieval_acc.pkl', 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../experiment/wikidata/jv/translated_retrieval_acc.pkl'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 191, in <module>
    do_evaluation(generator, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 72, in do_evaluation
    with open(f'../experiment/{args.retriever}/{args.lang}/{prefix}retrieval_acc.pkl', 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../experiment/wikidata/jv/translated_retrieval_acc.pkl'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 191, in <module>
    do_evaluation(generator, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 72, in do_evaluation
    with open(f'../experiment/{args.retriever}/{args.lang}/{prefix}retrieval_acc.pkl', 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../experiment/wikidata/jv/translated_retrieval_acc.pkl'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 191, in <module>
    do_evaluation(generator, args)
  File "/home/khalevy/Multilingual-Fig-QA/rag/main.py", line 72, in do_evaluation
    with open(f'../experiment/{args.retriever}/{args.lang}/{prefix}retrieval_acc.pkl', 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../experiment/wikidata/kn/translated_retrieval_acc.pkl'
slurmstepd: error: *** JOB 259080 ON babel-2-12 CANCELLED AT 2024-04-28T13:37:44 ***
